### ISSUE TITLE
'redraw' was not defined in this scope

### ISSUE THREAD

**Issue by PopKulture** [AbsolutRenal/Arduino-Pong#1]
I want to try this on my arduino esplora, but when I put it into the software, it gives me the error "'redraw' was not defined in this scope". Please?

**Comment by AbsolutRenal** [comment]
Hi,
I fixed the project tree to open it in Arduino software. So pull your repository and open EsploraTFTPongTEST.ino. I tried it few minutes ago so it should work. Let me know if you have any problem.
